Add Rust Tutorial
OUXT-Polaris/ros_handson pull request #23
Opened 2023-09-16 14:11 UTC by TakanoTaiga

safe_driveのチュートリアルとdockerfileにsafe_driveとrustのインストールを追加しました。

2023-09-18 15:31 UTC, kazuki0824 approved these changes

2023-09-18 15:50 UTC, kazuki0824 requested changes

2023-09-18 15:50 UTC, kazuki0824 commented on docs/safe_drive.md
> +  <buildtool_depend>ament_cmake</buildtool_depend>
https://github.com/tier4/safe_drive_tutorial/blob/main/msgtest/src/talker/package.xml
公式を参照するとここは必要なさそうですが、この行は必要そうでしょうか？

2023-09-18 15:50 UTC, kazuki0824 commented on docs/safe_drive.md
> +    <build_type>ament_cmake</build_type>
https://github.com/tier4/safe_drive_tutorial/blob/main/msgtest/src/talker/package.xml
公式を参照するとここはament_cargoのように見えますが、どうでしょうか？

2023-09-20 12:52 UTC, TakanoTaiga commented on docs/safe_drive.md
> +    <build_type>ament_cmake</build_type>
上のと同じく必要ないです。ご指摘ありがとうございます🙇

2023-09-23 00:47 UTC, hakuturu583 commented
linterが不可解な挙動して死んでる👀
確認します

2023-09-23 00:48 UTC, hakuturu583 commented
あー、これTwitter APIの仕様変わってリンク差し変わってる？

2023-09-23 01:36 UTC, TakanoTaiga commented
Elonめ

2023-09-23 01:41 UTC, TakanoTaiga commented
@hakuturu583 Twitterが終わってる問題どうする感じでしょうか？ (とりあえずでこのPRをMergeして欲しいお気持ち)

2023-10-02 06:48 UTC, hakuturu583 commented
サンプルコードをこちらに同時にPRを出してください。
https://github.com/OUXT-Polaris/ros_handson_packages

2023-10-05 13:07 UTC, TakanoTaiga commented
> サンプルコードをこちらに同時にPRを出してください。 https://github.com/OUXT-Polaris/ros_handson_packages

PR done. 確認お願いします

2023-10-06 16:33 UTC, hakuturu583 approved these changes

2023-10-06 16:33 UTC, merged