Add nav2 with map
OUXT-Polaris/ros_handson pull request #29
Opened 2023-10-15 06:21 UTC by koichirokato

以下の更新を実施しました。
- 地図を使用したNavigation2実行のページを追加
- 上記に伴う画像、コンフィグファイルの追加、Dockerfileの更新
- Navigation2のページの微修正

今後、今回追加したページにslam_toolboxなどを使用したオンライン/オフラインSLAMについても追加するつもりです。

2023-10-16 00:39 UTC, koichirokato commented
@hakuturu583 毎度お手数ですが内容問題ないか等レビューいただけますでしょうか🙏

2023-10-16 09:30 UTC, hakuturu583 requested changes

2023-10-16 09:30 UTC, hakuturu583 commented on docs/navigation_with_map.md
> +# 地図を使用したnavigation2での自律移動
この30行程度の教材をファイルを分けている理由は何でしょうか？
[こちら](https://github.com/OUXT-Polaris/ros_handson/blob/master/docs/navigation2.md)に統合したほうがよさそうと感じます。
また、新しいmarkdownを追加した場合は[このファイル](https://github.com/OUXT-Polaris/ros_handson/blob/master/mkdocs.yml)を編集しなくては教材を公開している静的ウェブサイトに反映されません。

2023-10-16 09:45 UTC, koichirokato commented on docs/navigation_with_map.md
> +# 地図を使用したnavigation2での自律移動
確認ありがとうございます。
ファイルを分けた理由は以下の2つです。
・もともとの教材の内容/流れをなるべく邪魔したくなかったため
・SLAMについて説明を追記する場合、ボリュームが大きくなると思ったため

既存の教材の流れを尊重しましたが、Navigation2のページに統合して良いとのことであればそちらに統合しようと思います。

Markdownの追加と反映についてありがとうございます。上記の対応含め必要であれば追記します。

2023-10-17 03:00 UTC, hakuturu583 commented on docs/navigation_with_map.md
> +# 地図を使用したnavigation2での自律移動
> 既存の教材の流れを尊重しましたが、Navigation2のページに統合して良いとのことであればそちらに統合しようと思います。

統合してもらって大丈夫です！

2023-10-17 03:50 UTC, hakuturu583 approved these changes

2023-10-17 03:50 UTC, merged